// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	BlockedEntry          string
	BlockedList           string
	BlockedListAppeal     string
	BlockedListInvite     string
	Channel               string
	Comment               string
	CommentClassification string
	CreatorSetting        string
	DelegatedModerator    string
	GorpMigrations        string
	Moderator             string
	Reaction              string
	ReactionType          string
}{
	BlockedEntry:          "blocked_entry",
	BlockedList:           "blocked_list",
	BlockedListAppeal:     "blocked_list_appeal",
	BlockedListInvite:     "blocked_list_invite",
	Channel:               "channel",
	Comment:               "comment",
	CommentClassification: "comment_classification",
	CreatorSetting:        "creator_setting",
	DelegatedModerator:    "delegated_moderator",
	GorpMigrations:        "gorp_migrations",
	Moderator:             "moderator",
	Reaction:              "reaction",
	ReactionType:          "reaction_type",
}
