// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// ContentOpinion is an object representing the database table.
type ContentOpinion struct {
	ID        uint64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ClaimID   null.String `boil:"claim_id" json:"claim_id,omitempty" toml:"claim_id" yaml:"claim_id,omitempty"`
	ChannelID null.String `boil:"channel_id" json:"channel_id,omitempty" toml:"channel_id" yaml:"channel_id,omitempty"`
	Signature null.String `boil:"signature" json:"signature,omitempty" toml:"signature" yaml:"signature,omitempty"`
	Signingts null.String `boil:"signingts" json:"signingts,omitempty" toml:"signingts" yaml:"signingts,omitempty"`
	Timestamp int         `boil:"timestamp" json:"timestamp" toml:"timestamp" yaml:"timestamp"`
	Rating    null.Int8   `boil:"rating" json:"rating,omitempty" toml:"rating" yaml:"rating,omitempty"`

	R *contentOpinionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L contentOpinionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ContentOpinionColumns = struct {
	ID        string
	ClaimID   string
	ChannelID string
	Signature string
	Signingts string
	Timestamp string
	Rating    string
}{
	ID:        "id",
	ClaimID:   "claim_id",
	ChannelID: "channel_id",
	Signature: "signature",
	Signingts: "signingts",
	Timestamp: "timestamp",
	Rating:    "rating",
}

// Generated where

var ContentOpinionWhere = struct {
	ID        whereHelperuint64
	ClaimID   whereHelpernull_String
	ChannelID whereHelpernull_String
	Signature whereHelpernull_String
	Signingts whereHelpernull_String
	Timestamp whereHelperint
	Rating    whereHelpernull_Int8
}{
	ID:        whereHelperuint64{field: "`content_opinion`.`id`"},
	ClaimID:   whereHelpernull_String{field: "`content_opinion`.`claim_id`"},
	ChannelID: whereHelpernull_String{field: "`content_opinion`.`channel_id`"},
	Signature: whereHelpernull_String{field: "`content_opinion`.`signature`"},
	Signingts: whereHelpernull_String{field: "`content_opinion`.`signingts`"},
	Timestamp: whereHelperint{field: "`content_opinion`.`timestamp`"},
	Rating:    whereHelpernull_Int8{field: "`content_opinion`.`rating`"},
}

// ContentOpinionRels is where relationship names are stored.
var ContentOpinionRels = struct {
	Channel string
}{
	Channel: "Channel",
}

// contentOpinionR is where relationships are stored.
type contentOpinionR struct {
	Channel *Channel
}

// NewStruct creates a new relationship struct
func (*contentOpinionR) NewStruct() *contentOpinionR {
	return &contentOpinionR{}
}

// contentOpinionL is where Load methods for each relationship are stored.
type contentOpinionL struct{}

var (
	contentOpinionAllColumns            = []string{"id", "claim_id", "channel_id", "signature", "signingts", "timestamp", "rating"}
	contentOpinionColumnsWithoutDefault = []string{"claim_id", "channel_id", "signature", "signingts", "timestamp"}
	contentOpinionColumnsWithDefault    = []string{"id", "rating"}
	contentOpinionPrimaryKeyColumns     = []string{"id"}
)

type (
	// ContentOpinionSlice is an alias for a slice of pointers to ContentOpinion.
	// This should generally be used opposed to []ContentOpinion.
	ContentOpinionSlice []*ContentOpinion

	contentOpinionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	contentOpinionType                 = reflect.TypeOf(&ContentOpinion{})
	contentOpinionMapping              = queries.MakeStructMapping(contentOpinionType)
	contentOpinionPrimaryKeyMapping, _ = queries.BindMapping(contentOpinionType, contentOpinionMapping, contentOpinionPrimaryKeyColumns)
	contentOpinionInsertCacheMut       sync.RWMutex
	contentOpinionInsertCache          = make(map[string]insertCache)
	contentOpinionUpdateCacheMut       sync.RWMutex
	contentOpinionUpdateCache          = make(map[string]updateCache)
	contentOpinionUpsertCacheMut       sync.RWMutex
	contentOpinionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single contentOpinion record from the query using the global executor.
func (q contentOpinionQuery) OneG() (*ContentOpinion, error) {
	return q.One(boil.GetDB())
}

// OneGP returns a single contentOpinion record from the query using the global executor, and panics on error.
func (q contentOpinionQuery) OneGP() *ContentOpinion {
	o, err := q.One(boil.GetDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// OneP returns a single contentOpinion record from the query, and panics on error.
func (q contentOpinionQuery) OneP(exec boil.Executor) *ContentOpinion {
	o, err := q.One(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single contentOpinion record from the query.
func (q contentOpinionQuery) One(exec boil.Executor) (*ContentOpinion, error) {
	o := &ContentOpinion{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: failed to execute a one query for content_opinion")
	}

	return o, nil
}

// AllG returns all ContentOpinion records from the query using the global executor.
func (q contentOpinionQuery) AllG() (ContentOpinionSlice, error) {
	return q.All(boil.GetDB())
}

// AllGP returns all ContentOpinion records from the query using the global executor, and panics on error.
func (q contentOpinionQuery) AllGP() ContentOpinionSlice {
	o, err := q.All(boil.GetDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// AllP returns all ContentOpinion records from the query, and panics on error.
func (q contentOpinionQuery) AllP(exec boil.Executor) ContentOpinionSlice {
	o, err := q.All(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all ContentOpinion records from the query.
func (q contentOpinionQuery) All(exec boil.Executor) (ContentOpinionSlice, error) {
	var o []*ContentOpinion

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to ContentOpinion slice")
	}

	return o, nil
}

// CountG returns the count of all ContentOpinion records in the query, and panics on error.
func (q contentOpinionQuery) CountG() (int64, error) {
	return q.Count(boil.GetDB())
}

// CountGP returns the count of all ContentOpinion records in the query using the global executor, and panics on error.
func (q contentOpinionQuery) CountGP() int64 {
	c, err := q.Count(boil.GetDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// CountP returns the count of all ContentOpinion records in the query, and panics on error.
func (q contentOpinionQuery) CountP(exec boil.Executor) int64 {
	c, err := q.Count(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all ContentOpinion records in the query.
func (q contentOpinionQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count content_opinion rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table, and panics on error.
func (q contentOpinionQuery) ExistsG() (bool, error) {
	return q.Exists(boil.GetDB())
}

// ExistsGP checks if the row exists in the table using the global executor, and panics on error.
func (q contentOpinionQuery) ExistsGP() bool {
	e, err := q.Exists(boil.GetDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ExistsP checks if the row exists in the table, and panics on error.
func (q contentOpinionQuery) ExistsP(exec boil.Executor) bool {
	e, err := q.Exists(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q contentOpinionQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if content_opinion exists")
	}

	return count > 0, nil
}

// Channel pointed to by the foreign key.
func (o *ContentOpinion) Channel(mods ...qm.QueryMod) channelQuery {
	queryMods := []qm.QueryMod{
		qm.Where("claim_id=?", o.ChannelID),
	}

	queryMods = append(queryMods, mods...)

	query := Channels(queryMods...)
	queries.SetFrom(query.Query, "`channel`")

	return query
}

// LoadChannel allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (contentOpinionL) LoadChannel(e boil.Executor, singular bool, maybeContentOpinion interface{}, mods queries.Applicator) error {
	var slice []*ContentOpinion
	var object *ContentOpinion

	if singular {
		object = maybeContentOpinion.(*ContentOpinion)
	} else {
		slice = *maybeContentOpinion.(*[]*ContentOpinion)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &contentOpinionR{}
		}
		if !queries.IsNil(object.ChannelID) {
			args = append(args, object.ChannelID)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &contentOpinionR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.ChannelID) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.ChannelID) {
				args = append(args, obj.ChannelID)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`channel`), qm.WhereIn(`claim_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Channel")
	}

	var resultSlice []*Channel
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Channel")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for channel")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for channel")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Channel = foreign
		if foreign.R == nil {
			foreign.R = &channelR{}
		}
		foreign.R.ContentOpinions = append(foreign.R.ContentOpinions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ChannelID, foreign.ClaimID) {
				local.R.Channel = foreign
				if foreign.R == nil {
					foreign.R = &channelR{}
				}
				foreign.R.ContentOpinions = append(foreign.R.ContentOpinions, local)
				break
			}
		}
	}

	return nil
}

// SetChannelG of the contentOpinion to the related item.
// Sets o.R.Channel to related.
// Adds o to related.R.ContentOpinions.
// Uses the global database handle.
func (o *ContentOpinion) SetChannelG(insert bool, related *Channel) error {
	return o.SetChannel(boil.GetDB(), insert, related)
}

// SetChannelP of the contentOpinion to the related item.
// Sets o.R.Channel to related.
// Adds o to related.R.ContentOpinions.
// Panics on error.
func (o *ContentOpinion) SetChannelP(exec boil.Executor, insert bool, related *Channel) {
	if err := o.SetChannel(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetChannelGP of the contentOpinion to the related item.
// Sets o.R.Channel to related.
// Adds o to related.R.ContentOpinions.
// Uses the global database handle and panics on error.
func (o *ContentOpinion) SetChannelGP(insert bool, related *Channel) {
	if err := o.SetChannel(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetChannel of the contentOpinion to the related item.
// Sets o.R.Channel to related.
// Adds o to related.R.ContentOpinions.
func (o *ContentOpinion) SetChannel(exec boil.Executor, insert bool, related *Channel) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `content_opinion` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"channel_id"}),
		strmangle.WhereClause("`", "`", 0, contentOpinionPrimaryKeyColumns),
	)
	values := []interface{}{related.ClaimID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ChannelID, related.ClaimID)
	if o.R == nil {
		o.R = &contentOpinionR{
			Channel: related,
		}
	} else {
		o.R.Channel = related
	}

	if related.R == nil {
		related.R = &channelR{
			ContentOpinions: ContentOpinionSlice{o},
		}
	} else {
		related.R.ContentOpinions = append(related.R.ContentOpinions, o)
	}

	return nil
}

// RemoveChannelG relationship.
// Sets o.R.Channel to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle.
func (o *ContentOpinion) RemoveChannelG(related *Channel) error {
	return o.RemoveChannel(boil.GetDB(), related)
}

// RemoveChannelP relationship.
// Sets o.R.Channel to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Panics on error.
func (o *ContentOpinion) RemoveChannelP(exec boil.Executor, related *Channel) {
	if err := o.RemoveChannel(exec, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveChannelGP relationship.
// Sets o.R.Channel to nil.
// Removes o from all passed in related items' relationships struct (Optional).
// Uses the global database handle and panics on error.
func (o *ContentOpinion) RemoveChannelGP(related *Channel) {
	if err := o.RemoveChannel(boil.GetDB(), related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// RemoveChannel relationship.
// Sets o.R.Channel to nil.
// Removes o from all passed in related items' relationships struct (Optional).
func (o *ContentOpinion) RemoveChannel(exec boil.Executor, related *Channel) error {
	var err error

	queries.SetScanner(&o.ChannelID, nil)
	if err = o.Update(exec, boil.Whitelist("channel_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.R.Channel = nil
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ContentOpinions {
		if queries.Equal(o.ChannelID, ri.ChannelID) {
			continue
		}

		ln := len(related.R.ContentOpinions)
		if ln > 1 && i < ln-1 {
			related.R.ContentOpinions[i] = related.R.ContentOpinions[ln-1]
		}
		related.R.ContentOpinions = related.R.ContentOpinions[:ln-1]
		break
	}
	return nil
}

// ContentOpinions retrieves all the records using an executor.
func ContentOpinions(mods ...qm.QueryMod) contentOpinionQuery {
	mods = append(mods, qm.From("`content_opinion`"))
	return contentOpinionQuery{NewQuery(mods...)}
}

// FindContentOpinionG retrieves a single record by ID.
func FindContentOpinionG(iD uint64, selectCols ...string) (*ContentOpinion, error) {
	return FindContentOpinion(boil.GetDB(), iD, selectCols...)
}

// FindContentOpinionP retrieves a single record by ID with an executor, and panics on error.
func FindContentOpinionP(exec boil.Executor, iD uint64, selectCols ...string) *ContentOpinion {
	retobj, err := FindContentOpinion(exec, iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindContentOpinionGP retrieves a single record by ID, and panics on error.
func FindContentOpinionGP(iD uint64, selectCols ...string) *ContentOpinion {
	retobj, err := FindContentOpinion(boil.GetDB(), iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindContentOpinion retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindContentOpinion(exec boil.Executor, iD uint64, selectCols ...string) (*ContentOpinion, error) {
	contentOpinionObj := &ContentOpinion{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `content_opinion` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, contentOpinionObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: unable to select from content_opinion")
	}

	return contentOpinionObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *ContentOpinion) InsertG(columns boil.Columns) error {
	return o.Insert(boil.GetDB(), columns)
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *ContentOpinion) InsertP(exec boil.Executor, columns boil.Columns) {
	if err := o.Insert(exec, columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *ContentOpinion) InsertGP(columns boil.Columns) {
	if err := o.Insert(boil.GetDB(), columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ContentOpinion) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("model: no content_opinion provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(contentOpinionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	contentOpinionInsertCacheMut.RLock()
	cache, cached := contentOpinionInsertCache[key]
	contentOpinionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			contentOpinionAllColumns,
			contentOpinionColumnsWithDefault,
			contentOpinionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(contentOpinionType, contentOpinionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(contentOpinionType, contentOpinionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `content_opinion` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `content_opinion` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `content_opinion` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, contentOpinionPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into content_opinion")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == contentOpinionMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for content_opinion")
	}

CacheNoHooks:
	if !cached {
		contentOpinionInsertCacheMut.Lock()
		contentOpinionInsertCache[key] = cache
		contentOpinionInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single ContentOpinion record using the global executor.
// See Update for more documentation.
func (o *ContentOpinion) UpdateG(columns boil.Columns) error {
	return o.Update(boil.GetDB(), columns)
}

// UpdateP uses an executor to update the ContentOpinion, and panics on error.
// See Update for more documentation.
func (o *ContentOpinion) UpdateP(exec boil.Executor, columns boil.Columns) {
	err := o.Update(exec, columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateGP a single ContentOpinion record using the global executor. Panics on error.
// See Update for more documentation.
func (o *ContentOpinion) UpdateGP(columns boil.Columns) {
	err := o.Update(boil.GetDB(), columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the ContentOpinion.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ContentOpinion) Update(exec boil.Executor, columns boil.Columns) error {
	var err error
	key := makeCacheKey(columns, nil)
	contentOpinionUpdateCacheMut.RLock()
	cache, cached := contentOpinionUpdateCache[key]
	contentOpinionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			contentOpinionAllColumns,
			contentOpinionPrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return errors.New("model: unable to update content_opinion, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `content_opinion` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, contentOpinionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(contentOpinionType, contentOpinionMapping, append(wl, contentOpinionPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "model: unable to update content_opinion row")
	}

	if !cached {
		contentOpinionUpdateCacheMut.Lock()
		contentOpinionUpdateCache[key] = cache
		contentOpinionUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q contentOpinionQuery) UpdateAllP(exec boil.Executor, cols M) {
	err := q.UpdateAll(exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllG updates all rows with the specified column values.
func (q contentOpinionQuery) UpdateAllG(cols M) error {
	return q.UpdateAll(boil.GetDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q contentOpinionQuery) UpdateAll(exec boil.Executor, cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec(exec)
	if err != nil {
		return errors.Wrap(err, "model: unable to update all for content_opinion")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ContentOpinionSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o ContentOpinionSlice) UpdateAllGP(cols M) {
	err := o.UpdateAll(boil.GetDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o ContentOpinionSlice) UpdateAllP(exec boil.Executor, cols M) {
	err := o.UpdateAll(exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ContentOpinionSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), contentOpinionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `content_opinion` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, contentOpinionPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "model: unable to update all in contentOpinion slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *ContentOpinion) UpsertG(updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(boil.GetDB(), updateColumns, insertColumns)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *ContentOpinion) UpsertGP(updateColumns, insertColumns boil.Columns) {
	if err := o.Upsert(boil.GetDB(), updateColumns, insertColumns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *ContentOpinion) UpsertP(exec boil.Executor, updateColumns, insertColumns boil.Columns) {
	if err := o.Upsert(exec, updateColumns, insertColumns); err != nil {
		panic(boil.WrapErr(err))
	}
}

var mySQLContentOpinionUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ContentOpinion) Upsert(exec boil.Executor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("model: no content_opinion provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(contentOpinionColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLContentOpinionUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	contentOpinionUpsertCacheMut.RLock()
	cache, cached := contentOpinionUpsertCache[key]
	contentOpinionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			contentOpinionAllColumns,
			contentOpinionColumnsWithDefault,
			contentOpinionColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			contentOpinionAllColumns,
			contentOpinionPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("model: unable to upsert content_opinion, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "content_opinion", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `content_opinion` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(contentOpinionType, contentOpinionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(contentOpinionType, contentOpinionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "model: unable to upsert for content_opinion")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == contentOpinionMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(contentOpinionType, contentOpinionMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "model: unable to retrieve unique values for content_opinion")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRow(cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for content_opinion")
	}

CacheNoHooks:
	if !cached {
		contentOpinionUpsertCacheMut.Lock()
		contentOpinionUpsertCache[key] = cache
		contentOpinionUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single ContentOpinion record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *ContentOpinion) DeleteG() error {
	return o.Delete(boil.GetDB())
}

// DeleteP deletes a single ContentOpinion record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *ContentOpinion) DeleteP(exec boil.Executor) {
	err := o.Delete(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteGP deletes a single ContentOpinion record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *ContentOpinion) DeleteGP() {
	err := o.Delete(boil.GetDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single ContentOpinion record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ContentOpinion) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("model: no ContentOpinion provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), contentOpinionPrimaryKeyMapping)
	sql := "DELETE FROM `content_opinion` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "model: unable to delete from content_opinion")
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q contentOpinionQuery) DeleteAllP(exec boil.Executor) {
	err := q.DeleteAll(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q contentOpinionQuery) DeleteAll(exec boil.Executor) error {
	if q.Query == nil {
		return errors.New("model: no contentOpinionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec(exec)
	if err != nil {
		return errors.Wrap(err, "model: unable to delete all from content_opinion")
	}

	return nil
}

// DeleteAllG deletes all rows in the slice.
func (o ContentOpinionSlice) DeleteAllG() error {
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o ContentOpinionSlice) DeleteAllP(exec boil.Executor) {
	err := o.DeleteAll(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o ContentOpinionSlice) DeleteAllGP() {
	err := o.DeleteAll(boil.GetDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ContentOpinionSlice) DeleteAll(exec boil.Executor) error {
	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), contentOpinionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `content_opinion` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, contentOpinionPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "model: unable to delete all from contentOpinion slice")
	}

	return nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *ContentOpinion) ReloadG() error {
	if o == nil {
		return errors.New("model: no ContentOpinion provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *ContentOpinion) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadGP refetches the object from the database and panics on error.
func (o *ContentOpinion) ReloadGP() {
	if err := o.Reload(boil.GetDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ContentOpinion) Reload(exec boil.Executor) error {
	ret, err := FindContentOpinion(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ContentOpinionSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("model: empty ContentOpinionSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *ContentOpinionSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *ContentOpinionSlice) ReloadAllGP() {
	if err := o.ReloadAll(boil.GetDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ContentOpinionSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ContentOpinionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), contentOpinionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `content_opinion`.* FROM `content_opinion` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, contentOpinionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in ContentOpinionSlice")
	}

	*o = slice

	return nil
}

// ContentOpinionExistsG checks if the ContentOpinion row exists.
func ContentOpinionExistsG(iD uint64) (bool, error) {
	return ContentOpinionExists(boil.GetDB(), iD)
}

// ContentOpinionExistsP checks if the ContentOpinion row exists. Panics on error.
func ContentOpinionExistsP(exec boil.Executor, iD uint64) bool {
	e, err := ContentOpinionExists(exec, iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ContentOpinionExistsGP checks if the ContentOpinion row exists. Panics on error.
func ContentOpinionExistsGP(iD uint64) bool {
	e, err := ContentOpinionExists(boil.GetDB(), iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ContentOpinionExists checks if the ContentOpinion row exists.
func ContentOpinionExists(exec boil.Executor, iD uint64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `content_opinion` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if content_opinion exists")
	}

	return exists, nil
}
