// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// DelegatedModerator is an object representing the database table.
type DelegatedModerator struct {
	ID               uint64    `boil:"id" json:"id" toml:"id" yaml:"id"`
	ModChannelID     string    `boil:"mod_channel_id" json:"mod_channel_id" toml:"mod_channel_id" yaml:"mod_channel_id"`
	CreatorChannelID string    `boil:"creator_channel_id" json:"creator_channel_id" toml:"creator_channel_id" yaml:"creator_channel_id"`
	Permissons       uint64    `boil:"permissons" json:"permissons" toml:"permissons" yaml:"permissons"`
	CreatedAt        time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt        time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *delegatedModeratorR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L delegatedModeratorL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DelegatedModeratorColumns = struct {
	ID               string
	ModChannelID     string
	CreatorChannelID string
	Permissons       string
	CreatedAt        string
	UpdatedAt        string
}{
	ID:               "id",
	ModChannelID:     "mod_channel_id",
	CreatorChannelID: "creator_channel_id",
	Permissons:       "permissons",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

// Generated where

var DelegatedModeratorWhere = struct {
	ID               whereHelperuint64
	ModChannelID     whereHelperstring
	CreatorChannelID whereHelperstring
	Permissons       whereHelperuint64
	CreatedAt        whereHelpertime_Time
	UpdatedAt        whereHelpertime_Time
}{
	ID:               whereHelperuint64{field: "`delegated_moderator`.`id`"},
	ModChannelID:     whereHelperstring{field: "`delegated_moderator`.`mod_channel_id`"},
	CreatorChannelID: whereHelperstring{field: "`delegated_moderator`.`creator_channel_id`"},
	Permissons:       whereHelperuint64{field: "`delegated_moderator`.`permissons`"},
	CreatedAt:        whereHelpertime_Time{field: "`delegated_moderator`.`created_at`"},
	UpdatedAt:        whereHelpertime_Time{field: "`delegated_moderator`.`updated_at`"},
}

// DelegatedModeratorRels is where relationship names are stored.
var DelegatedModeratorRels = struct {
	ModChannel     string
	CreatorChannel string
}{
	ModChannel:     "ModChannel",
	CreatorChannel: "CreatorChannel",
}

// delegatedModeratorR is where relationships are stored.
type delegatedModeratorR struct {
	ModChannel     *Channel
	CreatorChannel *Channel
}

// NewStruct creates a new relationship struct
func (*delegatedModeratorR) NewStruct() *delegatedModeratorR {
	return &delegatedModeratorR{}
}

// delegatedModeratorL is where Load methods for each relationship are stored.
type delegatedModeratorL struct{}

var (
	delegatedModeratorAllColumns            = []string{"id", "mod_channel_id", "creator_channel_id", "permissons", "created_at", "updated_at"}
	delegatedModeratorColumnsWithoutDefault = []string{"mod_channel_id", "creator_channel_id"}
	delegatedModeratorColumnsWithDefault    = []string{"id", "permissons", "created_at", "updated_at"}
	delegatedModeratorPrimaryKeyColumns     = []string{"id"}
)

type (
	// DelegatedModeratorSlice is an alias for a slice of pointers to DelegatedModerator.
	// This should generally be used opposed to []DelegatedModerator.
	DelegatedModeratorSlice []*DelegatedModerator

	delegatedModeratorQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	delegatedModeratorType                 = reflect.TypeOf(&DelegatedModerator{})
	delegatedModeratorMapping              = queries.MakeStructMapping(delegatedModeratorType)
	delegatedModeratorPrimaryKeyMapping, _ = queries.BindMapping(delegatedModeratorType, delegatedModeratorMapping, delegatedModeratorPrimaryKeyColumns)
	delegatedModeratorInsertCacheMut       sync.RWMutex
	delegatedModeratorInsertCache          = make(map[string]insertCache)
	delegatedModeratorUpdateCacheMut       sync.RWMutex
	delegatedModeratorUpdateCache          = make(map[string]updateCache)
	delegatedModeratorUpsertCacheMut       sync.RWMutex
	delegatedModeratorUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single delegatedModerator record from the query using the global executor.
func (q delegatedModeratorQuery) OneG() (*DelegatedModerator, error) {
	return q.One(boil.GetDB())
}

// OneGP returns a single delegatedModerator record from the query using the global executor, and panics on error.
func (q delegatedModeratorQuery) OneGP() *DelegatedModerator {
	o, err := q.One(boil.GetDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// OneP returns a single delegatedModerator record from the query, and panics on error.
func (q delegatedModeratorQuery) OneP(exec boil.Executor) *DelegatedModerator {
	o, err := q.One(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single delegatedModerator record from the query.
func (q delegatedModeratorQuery) One(exec boil.Executor) (*DelegatedModerator, error) {
	o := &DelegatedModerator{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: failed to execute a one query for delegated_moderator")
	}

	return o, nil
}

// AllG returns all DelegatedModerator records from the query using the global executor.
func (q delegatedModeratorQuery) AllG() (DelegatedModeratorSlice, error) {
	return q.All(boil.GetDB())
}

// AllGP returns all DelegatedModerator records from the query using the global executor, and panics on error.
func (q delegatedModeratorQuery) AllGP() DelegatedModeratorSlice {
	o, err := q.All(boil.GetDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// AllP returns all DelegatedModerator records from the query, and panics on error.
func (q delegatedModeratorQuery) AllP(exec boil.Executor) DelegatedModeratorSlice {
	o, err := q.All(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all DelegatedModerator records from the query.
func (q delegatedModeratorQuery) All(exec boil.Executor) (DelegatedModeratorSlice, error) {
	var o []*DelegatedModerator

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to DelegatedModerator slice")
	}

	return o, nil
}

// CountG returns the count of all DelegatedModerator records in the query, and panics on error.
func (q delegatedModeratorQuery) CountG() (int64, error) {
	return q.Count(boil.GetDB())
}

// CountGP returns the count of all DelegatedModerator records in the query using the global executor, and panics on error.
func (q delegatedModeratorQuery) CountGP() int64 {
	c, err := q.Count(boil.GetDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// CountP returns the count of all DelegatedModerator records in the query, and panics on error.
func (q delegatedModeratorQuery) CountP(exec boil.Executor) int64 {
	c, err := q.Count(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all DelegatedModerator records in the query.
func (q delegatedModeratorQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count delegated_moderator rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table, and panics on error.
func (q delegatedModeratorQuery) ExistsG() (bool, error) {
	return q.Exists(boil.GetDB())
}

// ExistsGP checks if the row exists in the table using the global executor, and panics on error.
func (q delegatedModeratorQuery) ExistsGP() bool {
	e, err := q.Exists(boil.GetDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ExistsP checks if the row exists in the table, and panics on error.
func (q delegatedModeratorQuery) ExistsP(exec boil.Executor) bool {
	e, err := q.Exists(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q delegatedModeratorQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if delegated_moderator exists")
	}

	return count > 0, nil
}

// ModChannel pointed to by the foreign key.
func (o *DelegatedModerator) ModChannel(mods ...qm.QueryMod) channelQuery {
	queryMods := []qm.QueryMod{
		qm.Where("claim_id=?", o.ModChannelID),
	}

	queryMods = append(queryMods, mods...)

	query := Channels(queryMods...)
	queries.SetFrom(query.Query, "`channel`")

	return query
}

// CreatorChannel pointed to by the foreign key.
func (o *DelegatedModerator) CreatorChannel(mods ...qm.QueryMod) channelQuery {
	queryMods := []qm.QueryMod{
		qm.Where("claim_id=?", o.CreatorChannelID),
	}

	queryMods = append(queryMods, mods...)

	query := Channels(queryMods...)
	queries.SetFrom(query.Query, "`channel`")

	return query
}

// LoadModChannel allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (delegatedModeratorL) LoadModChannel(e boil.Executor, singular bool, maybeDelegatedModerator interface{}, mods queries.Applicator) error {
	var slice []*DelegatedModerator
	var object *DelegatedModerator

	if singular {
		object = maybeDelegatedModerator.(*DelegatedModerator)
	} else {
		slice = *maybeDelegatedModerator.(*[]*DelegatedModerator)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &delegatedModeratorR{}
		}
		args = append(args, object.ModChannelID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &delegatedModeratorR{}
			}

			for _, a := range args {
				if a == obj.ModChannelID {
					continue Outer
				}
			}

			args = append(args, obj.ModChannelID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`channel`), qm.WhereIn(`claim_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Channel")
	}

	var resultSlice []*Channel
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Channel")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for channel")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for channel")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ModChannel = foreign
		if foreign.R == nil {
			foreign.R = &channelR{}
		}
		foreign.R.ModChannelDelegatedModerators = append(foreign.R.ModChannelDelegatedModerators, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ModChannelID == foreign.ClaimID {
				local.R.ModChannel = foreign
				if foreign.R == nil {
					foreign.R = &channelR{}
				}
				foreign.R.ModChannelDelegatedModerators = append(foreign.R.ModChannelDelegatedModerators, local)
				break
			}
		}
	}

	return nil
}

// LoadCreatorChannel allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (delegatedModeratorL) LoadCreatorChannel(e boil.Executor, singular bool, maybeDelegatedModerator interface{}, mods queries.Applicator) error {
	var slice []*DelegatedModerator
	var object *DelegatedModerator

	if singular {
		object = maybeDelegatedModerator.(*DelegatedModerator)
	} else {
		slice = *maybeDelegatedModerator.(*[]*DelegatedModerator)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &delegatedModeratorR{}
		}
		args = append(args, object.CreatorChannelID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &delegatedModeratorR{}
			}

			for _, a := range args {
				if a == obj.CreatorChannelID {
					continue Outer
				}
			}

			args = append(args, obj.CreatorChannelID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`channel`), qm.WhereIn(`claim_id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Channel")
	}

	var resultSlice []*Channel
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Channel")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for channel")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for channel")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreatorChannel = foreign
		if foreign.R == nil {
			foreign.R = &channelR{}
		}
		foreign.R.CreatorChannelDelegatedModerators = append(foreign.R.CreatorChannelDelegatedModerators, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CreatorChannelID == foreign.ClaimID {
				local.R.CreatorChannel = foreign
				if foreign.R == nil {
					foreign.R = &channelR{}
				}
				foreign.R.CreatorChannelDelegatedModerators = append(foreign.R.CreatorChannelDelegatedModerators, local)
				break
			}
		}
	}

	return nil
}

// SetModChannelG of the delegatedModerator to the related item.
// Sets o.R.ModChannel to related.
// Adds o to related.R.ModChannelDelegatedModerators.
// Uses the global database handle.
func (o *DelegatedModerator) SetModChannelG(insert bool, related *Channel) error {
	return o.SetModChannel(boil.GetDB(), insert, related)
}

// SetModChannelP of the delegatedModerator to the related item.
// Sets o.R.ModChannel to related.
// Adds o to related.R.ModChannelDelegatedModerators.
// Panics on error.
func (o *DelegatedModerator) SetModChannelP(exec boil.Executor, insert bool, related *Channel) {
	if err := o.SetModChannel(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetModChannelGP of the delegatedModerator to the related item.
// Sets o.R.ModChannel to related.
// Adds o to related.R.ModChannelDelegatedModerators.
// Uses the global database handle and panics on error.
func (o *DelegatedModerator) SetModChannelGP(insert bool, related *Channel) {
	if err := o.SetModChannel(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetModChannel of the delegatedModerator to the related item.
// Sets o.R.ModChannel to related.
// Adds o to related.R.ModChannelDelegatedModerators.
func (o *DelegatedModerator) SetModChannel(exec boil.Executor, insert bool, related *Channel) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `delegated_moderator` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"mod_channel_id"}),
		strmangle.WhereClause("`", "`", 0, delegatedModeratorPrimaryKeyColumns),
	)
	values := []interface{}{related.ClaimID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ModChannelID = related.ClaimID
	if o.R == nil {
		o.R = &delegatedModeratorR{
			ModChannel: related,
		}
	} else {
		o.R.ModChannel = related
	}

	if related.R == nil {
		related.R = &channelR{
			ModChannelDelegatedModerators: DelegatedModeratorSlice{o},
		}
	} else {
		related.R.ModChannelDelegatedModerators = append(related.R.ModChannelDelegatedModerators, o)
	}

	return nil
}

// SetCreatorChannelG of the delegatedModerator to the related item.
// Sets o.R.CreatorChannel to related.
// Adds o to related.R.CreatorChannelDelegatedModerators.
// Uses the global database handle.
func (o *DelegatedModerator) SetCreatorChannelG(insert bool, related *Channel) error {
	return o.SetCreatorChannel(boil.GetDB(), insert, related)
}

// SetCreatorChannelP of the delegatedModerator to the related item.
// Sets o.R.CreatorChannel to related.
// Adds o to related.R.CreatorChannelDelegatedModerators.
// Panics on error.
func (o *DelegatedModerator) SetCreatorChannelP(exec boil.Executor, insert bool, related *Channel) {
	if err := o.SetCreatorChannel(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetCreatorChannelGP of the delegatedModerator to the related item.
// Sets o.R.CreatorChannel to related.
// Adds o to related.R.CreatorChannelDelegatedModerators.
// Uses the global database handle and panics on error.
func (o *DelegatedModerator) SetCreatorChannelGP(insert bool, related *Channel) {
	if err := o.SetCreatorChannel(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetCreatorChannel of the delegatedModerator to the related item.
// Sets o.R.CreatorChannel to related.
// Adds o to related.R.CreatorChannelDelegatedModerators.
func (o *DelegatedModerator) SetCreatorChannel(exec boil.Executor, insert bool, related *Channel) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `delegated_moderator` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"creator_channel_id"}),
		strmangle.WhereClause("`", "`", 0, delegatedModeratorPrimaryKeyColumns),
	)
	values := []interface{}{related.ClaimID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CreatorChannelID = related.ClaimID
	if o.R == nil {
		o.R = &delegatedModeratorR{
			CreatorChannel: related,
		}
	} else {
		o.R.CreatorChannel = related
	}

	if related.R == nil {
		related.R = &channelR{
			CreatorChannelDelegatedModerators: DelegatedModeratorSlice{o},
		}
	} else {
		related.R.CreatorChannelDelegatedModerators = append(related.R.CreatorChannelDelegatedModerators, o)
	}

	return nil
}

// DelegatedModerators retrieves all the records using an executor.
func DelegatedModerators(mods ...qm.QueryMod) delegatedModeratorQuery {
	mods = append(mods, qm.From("`delegated_moderator`"))
	return delegatedModeratorQuery{NewQuery(mods...)}
}

// FindDelegatedModeratorG retrieves a single record by ID.
func FindDelegatedModeratorG(iD uint64, selectCols ...string) (*DelegatedModerator, error) {
	return FindDelegatedModerator(boil.GetDB(), iD, selectCols...)
}

// FindDelegatedModeratorP retrieves a single record by ID with an executor, and panics on error.
func FindDelegatedModeratorP(exec boil.Executor, iD uint64, selectCols ...string) *DelegatedModerator {
	retobj, err := FindDelegatedModerator(exec, iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindDelegatedModeratorGP retrieves a single record by ID, and panics on error.
func FindDelegatedModeratorGP(iD uint64, selectCols ...string) *DelegatedModerator {
	retobj, err := FindDelegatedModerator(boil.GetDB(), iD, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindDelegatedModerator retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDelegatedModerator(exec boil.Executor, iD uint64, selectCols ...string) (*DelegatedModerator, error) {
	delegatedModeratorObj := &DelegatedModerator{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `delegated_moderator` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, delegatedModeratorObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: unable to select from delegated_moderator")
	}

	return delegatedModeratorObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *DelegatedModerator) InsertG(columns boil.Columns) error {
	return o.Insert(boil.GetDB(), columns)
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *DelegatedModerator) InsertP(exec boil.Executor, columns boil.Columns) {
	if err := o.Insert(exec, columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *DelegatedModerator) InsertGP(columns boil.Columns) {
	if err := o.Insert(boil.GetDB(), columns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DelegatedModerator) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("model: no delegated_moderator provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(delegatedModeratorColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	delegatedModeratorInsertCacheMut.RLock()
	cache, cached := delegatedModeratorInsertCache[key]
	delegatedModeratorInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			delegatedModeratorAllColumns,
			delegatedModeratorColumnsWithDefault,
			delegatedModeratorColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(delegatedModeratorType, delegatedModeratorMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(delegatedModeratorType, delegatedModeratorMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `delegated_moderator` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `delegated_moderator` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `delegated_moderator` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, delegatedModeratorPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into delegated_moderator")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == delegatedModeratorMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for delegated_moderator")
	}

CacheNoHooks:
	if !cached {
		delegatedModeratorInsertCacheMut.Lock()
		delegatedModeratorInsertCache[key] = cache
		delegatedModeratorInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single DelegatedModerator record using the global executor.
// See Update for more documentation.
func (o *DelegatedModerator) UpdateG(columns boil.Columns) error {
	return o.Update(boil.GetDB(), columns)
}

// UpdateP uses an executor to update the DelegatedModerator, and panics on error.
// See Update for more documentation.
func (o *DelegatedModerator) UpdateP(exec boil.Executor, columns boil.Columns) {
	err := o.Update(exec, columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateGP a single DelegatedModerator record using the global executor. Panics on error.
// See Update for more documentation.
func (o *DelegatedModerator) UpdateGP(columns boil.Columns) {
	err := o.Update(boil.GetDB(), columns)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the DelegatedModerator.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DelegatedModerator) Update(exec boil.Executor, columns boil.Columns) error {
	var err error
	key := makeCacheKey(columns, nil)
	delegatedModeratorUpdateCacheMut.RLock()
	cache, cached := delegatedModeratorUpdateCache[key]
	delegatedModeratorUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			delegatedModeratorAllColumns,
			delegatedModeratorPrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return errors.New("model: unable to update delegated_moderator, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `delegated_moderator` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, delegatedModeratorPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(delegatedModeratorType, delegatedModeratorMapping, append(wl, delegatedModeratorPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "model: unable to update delegated_moderator row")
	}

	if !cached {
		delegatedModeratorUpdateCacheMut.Lock()
		delegatedModeratorUpdateCache[key] = cache
		delegatedModeratorUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q delegatedModeratorQuery) UpdateAllP(exec boil.Executor, cols M) {
	err := q.UpdateAll(exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllG updates all rows with the specified column values.
func (q delegatedModeratorQuery) UpdateAllG(cols M) error {
	return q.UpdateAll(boil.GetDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q delegatedModeratorQuery) UpdateAll(exec boil.Executor, cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec(exec)
	if err != nil {
		return errors.Wrap(err, "model: unable to update all for delegated_moderator")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o DelegatedModeratorSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o DelegatedModeratorSlice) UpdateAllGP(cols M) {
	err := o.UpdateAll(boil.GetDB(), cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o DelegatedModeratorSlice) UpdateAllP(exec boil.Executor, cols M) {
	err := o.UpdateAll(exec, cols)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DelegatedModeratorSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), delegatedModeratorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `delegated_moderator` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, delegatedModeratorPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "model: unable to update all in delegatedModerator slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *DelegatedModerator) UpsertG(updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(boil.GetDB(), updateColumns, insertColumns)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *DelegatedModerator) UpsertGP(updateColumns, insertColumns boil.Columns) {
	if err := o.Upsert(boil.GetDB(), updateColumns, insertColumns); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *DelegatedModerator) UpsertP(exec boil.Executor, updateColumns, insertColumns boil.Columns) {
	if err := o.Upsert(exec, updateColumns, insertColumns); err != nil {
		panic(boil.WrapErr(err))
	}
}

var mySQLDelegatedModeratorUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DelegatedModerator) Upsert(exec boil.Executor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("model: no delegated_moderator provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(delegatedModeratorColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLDelegatedModeratorUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	delegatedModeratorUpsertCacheMut.RLock()
	cache, cached := delegatedModeratorUpsertCache[key]
	delegatedModeratorUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			delegatedModeratorAllColumns,
			delegatedModeratorColumnsWithDefault,
			delegatedModeratorColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			delegatedModeratorAllColumns,
			delegatedModeratorPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("model: unable to upsert delegated_moderator, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "delegated_moderator", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `delegated_moderator` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(delegatedModeratorType, delegatedModeratorMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(delegatedModeratorType, delegatedModeratorMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "model: unable to upsert for delegated_moderator")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == delegatedModeratorMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(delegatedModeratorType, delegatedModeratorMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "model: unable to retrieve unique values for delegated_moderator")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, nzUniqueCols...)
	}

	err = exec.QueryRow(cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "model: unable to populate default values for delegated_moderator")
	}

CacheNoHooks:
	if !cached {
		delegatedModeratorUpsertCacheMut.Lock()
		delegatedModeratorUpsertCache[key] = cache
		delegatedModeratorUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single DelegatedModerator record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *DelegatedModerator) DeleteG() error {
	return o.Delete(boil.GetDB())
}

// DeleteP deletes a single DelegatedModerator record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *DelegatedModerator) DeleteP(exec boil.Executor) {
	err := o.Delete(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteGP deletes a single DelegatedModerator record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *DelegatedModerator) DeleteGP() {
	err := o.Delete(boil.GetDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single DelegatedModerator record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DelegatedModerator) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("model: no DelegatedModerator provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), delegatedModeratorPrimaryKeyMapping)
	sql := "DELETE FROM `delegated_moderator` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "model: unable to delete from delegated_moderator")
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q delegatedModeratorQuery) DeleteAllP(exec boil.Executor) {
	err := q.DeleteAll(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q delegatedModeratorQuery) DeleteAll(exec boil.Executor) error {
	if q.Query == nil {
		return errors.New("model: no delegatedModeratorQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec(exec)
	if err != nil {
		return errors.Wrap(err, "model: unable to delete all from delegated_moderator")
	}

	return nil
}

// DeleteAllG deletes all rows in the slice.
func (o DelegatedModeratorSlice) DeleteAllG() error {
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o DelegatedModeratorSlice) DeleteAllP(exec boil.Executor) {
	err := o.DeleteAll(exec)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o DelegatedModeratorSlice) DeleteAllGP() {
	err := o.DeleteAll(boil.GetDB())
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DelegatedModeratorSlice) DeleteAll(exec boil.Executor) error {
	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), delegatedModeratorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `delegated_moderator` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, delegatedModeratorPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "model: unable to delete all from delegatedModerator slice")
	}

	return nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *DelegatedModerator) ReloadG() error {
	if o == nil {
		return errors.New("model: no DelegatedModerator provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *DelegatedModerator) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadGP refetches the object from the database and panics on error.
func (o *DelegatedModerator) ReloadGP() {
	if err := o.Reload(boil.GetDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DelegatedModerator) Reload(exec boil.Executor) error {
	ret, err := FindDelegatedModerator(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DelegatedModeratorSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("model: empty DelegatedModeratorSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *DelegatedModeratorSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *DelegatedModeratorSlice) ReloadAllGP() {
	if err := o.ReloadAll(boil.GetDB()); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DelegatedModeratorSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DelegatedModeratorSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), delegatedModeratorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `delegated_moderator`.* FROM `delegated_moderator` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, delegatedModeratorPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in DelegatedModeratorSlice")
	}

	*o = slice

	return nil
}

// DelegatedModeratorExistsG checks if the DelegatedModerator row exists.
func DelegatedModeratorExistsG(iD uint64) (bool, error) {
	return DelegatedModeratorExists(boil.GetDB(), iD)
}

// DelegatedModeratorExistsP checks if the DelegatedModerator row exists. Panics on error.
func DelegatedModeratorExistsP(exec boil.Executor, iD uint64) bool {
	e, err := DelegatedModeratorExists(exec, iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// DelegatedModeratorExistsGP checks if the DelegatedModerator row exists. Panics on error.
func DelegatedModeratorExistsGP(iD uint64) bool {
	e, err := DelegatedModeratorExists(boil.GetDB(), iD)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// DelegatedModeratorExists checks if the DelegatedModerator row exists.
func DelegatedModeratorExists(exec boil.Executor, iD uint64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `delegated_moderator` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if delegated_moderator exists")
	}

	return exists, nil
}
