version: "2"

run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    revive:
      rules:
        - name: exported
          disabled: true
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
  exclusions:
    paths:
      - model
      - migration
      - server/services/v1/rpc
    rules:
      - path: "server/lbry/channel.go"
        text: "newChannel"
        linters:
          - unused

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - localmodule
        - default
    gofmt:
      simplify: true

issues:
  uniq-by-line: true
