os: linux
dist: focal
language: go
go_import_path: github.com/OdyseeTeam/commentron

go: 1.18.x

install: true

services:
  - mysql
  - docker

before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS commentron;'
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS social;'
  - mysql -u root -e "CREATE USER 'lbry-rw'@'localhost' IDENTIFIED BY 'lbry';"
  - mysql -u root -e "CREATE USER 'lbry-ro'@'localhost' IDENTIFIED BY 'lbry';"
  - mysql -u root -e "GRANT ALL ON commentron.* TO 'lbry-rw'@'localhost';"
  - mysql -u root -e "GRANT SELECT ON commentron.* TO 'lbry-ro'@'localhost';"
  - mysql -u root -e "GRANT ALL ON social.* TO 'lbry-rw'@'localhost';"
  - sudo service mysql restart

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

script:
  - ./scripts/build.sh
  - ./scripts/lint.sh
  - source ./scripts/setup.sh
  - ./bin/commentron serve &
  - sleep 5s
  - "curl -i -H 'Accept: application/json' -H 'Content-Type: application/json' http://localhost:5900"
  - go test ./...
  - go mod tidy
  - git diff --exit-code
  - ./scripts/gen_models.sh
  - sqlboiler --version  # useful for diagnosing diffs below
  - git diff --exit-code
  - ./bin/commentron test

deploy:
  # creates and publishes new docker image per branch
  - provider: script
    script: bash docker/docker.sh
    skip_cleanup: true
    on:
      all_branches: true