os: linux
dist: xenial
language: go
go_import_path: github.com/lbryio/commentron

go: 1.13.4

install: true

services:
  - mysql
  - docker

before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS lbry;'
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS lbrytest;'
  - mysql -u root -e "CREATE USER 'lbry'@'localhost' IDENTIFIED BY 'lbry';"
  - mysql -u root -e "GRANT ALL ON lbry.* TO 'lbry'@'localhost';"
  - mysql -u root -e "GRANT ALL ON lbrytest.* TO 'lbry'@'localhost';"
  - sudo service mysql restart

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

script:
  - ./scripts/build.sh
  - go test ./...
  - ./scripts/lint.sh
  - go mod tidy
  - git diff --exit-code

deploy:
  # creates and publishes new docker image per branch
  - provider: script
    script: bash docker/docker.sh
    skip_cleanup: true
    on:
      all_branches: true