version: "3.7"

services:
  mysql:
    image: percona:ps-8.0
    restart: "no"
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=commentron
      - MYSQL_USER=commentron
      - MYSQL_PASSWORD=commentron
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - data:/var/lib/mysql"
  commentron:
    image: odyseeteam/commentron:master
    restart: "no"
    ports:
      - "5900:5900"
    environment:
      - MYSQL_DSN=commentron:commentron@tcp(mysql:3306)/commentron
      - AUTH_TOKEN=<token>
    depends_on:
      - mysql
    entrypoint: wait-for-it -t 0 mysql:3306 -- ./commentron serve
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data: