# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:5900/api/v2
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "comment.List",
  "params": {
    "page":1,
    "page_size":10,
    "sort_by":0,
    "author_claim_id": "cb7ea953be131d156a780ff400414a187123e589",
    "requestor_channel_name":"@thomas.zarebczan",
    "requestor_channel_id":"cb7ea953be131d156a780ff400414a187123e589",
    "signature":"fb31a514a13194b22dc111118de253dbdcecf922dead14747f835266a33eff820b62da0e76c638698294194131bf576d08d6870cfabac9a9ca666b49400ad225",
    "signing_ts":"1632928896"
  }
}



###
