# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:5921/api/v2
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "comment.GetClaimComments",
  "params": {
    "claim_id": "81f80f4232373f99f2a02aa0399e311238d3901e"
  }
}



###
