# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:5900/api/v2
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": null,
  "method": "comment.Create",
  "params": {
    "claim_id": "85f25238e4d2fc8e79772673d67c4cbe5dbe3006",
    "comment": "<stkr>:mysticker:<stkr>",
    "channel_id": "144b700dc39e97bb2347fbd9453d985eab79757f",
    "channel_name": "@🌹❤️😍Amirul😍❤️🌹",
    "support_tx_id": "dbf429961fdfde983d45da87d16febc3fd69be0f706d5aa71fceb5973c769265",
    "signature": "e8ad5dbd660365efd1646a9b5d82323efc550712a7a291aa3e715e31641cc57b18241a132ebed28a848086fca6e200a735281c631c7474b01b4c32851ea3dd57",
    "signing_ts": "1561669624",
    "sticker": true
  }
}

###
