# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:5900/api/v2
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "reaction.List",
  "params": {
    "comment_ids": "0fa2eacf0b91fa3187e87733f103418e51f0c40d0b06b67c5d6d3ff2c13b2925",
    "channel_name": "@dtrdtr",
    "channel_id": "d97913f183fa3f4c7133f6492963371b9021cf64"
  }
}



###
