# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:5900/api/v2
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": null,
  "method": "reaction.React",
  "params": {
    "comment_ids": "fffa4f879be927ff25362fe88cee944d974a2fd265be9f54135a1a5c5c23435a",
    "channel_name": "@bbbbb",
    "channel_id": "9cb713f01bf247a0e03170b5ed00d5161340c486",
    "signing_ts": "1234567",
    "rating": 1
  }
}

###

