POST http://localhost:5279/
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "comment_abandon",
  "params": {
    "comment_id": "44e5705cf32d47ac21c889e2d174858053ffe852008a68c3ebc6ef5d997f6371"
  }
}