package flags

import "regexp"

var flaggedPhrases = []*regexp.Regexp{
	regexp.MustCompile(`.*per day online work.*`),
	regexp.MustCompile(`.*follow me back please.*`),
	regexp.MustCompile(`.*I earns every weeks.*`),
	regexp.MustCompile(`.*A White House Memoir by John Bolton.*`),
	regexp.MustCompile(`.*REPOST THIS VIDEO AND I WILL REPOST 2 YOURS.*`),
	regexp.MustCompile(`.*All i did was simple online work from.*`),
	regexp.MustCompile(`.*hr provide by Google.*`),
	regexp.MustCompile(`.*I heard about this job 3 months.*`),
	regexp.MustCompile(`.*hour for doing online work from home.*`),
	regexp.MustCompile(`.*adshrink.it.*`),
	regexp.MustCompile(`.*I get paid over \$.* per hour working from home.*`),
	regexp.MustCompile(`.*Free Money - After.*`),
	regexp.MustCompile(`.*Real online home based job.*`),
	regexp.MustCompile(`.*I getting Paid upto \$.* this week.*`),
	regexp.MustCompile(`.*Get your financial freedom out of the hands.*`),
	regexp.MustCompile(`.*simple online job from home.*`),
	regexp.MustCompile(`.*She has been fired for .* months but last month.*`),
	regexp.MustCompile(`.*She has been laid off for .* months but last.*`),
	regexp.MustCompile(`.*makes \$.*hour.* on the computer.*`),
	regexp.MustCompile(`.*makes \$.*hour.* on the laptop.*`),
	regexp.MustCompile(`.*makes \$.*hour.* on the internet.*`),
	regexp.MustCompile(`.*peau de mouton qui habille et camoufle un loup.*`),
	regexp.MustCompile(`.*\$.*-\$.* per month on the web.*`),
	regexp.MustCompile(`.*Help the channel and join you these awesome pages to obtain free crypto coins.*`),
	regexp.MustCompile(`.*https://lbry.tv/\$./invite/@NiQo:5.*`),
	regexp.MustCompile(`.*PART TIME ONLINE JOBS.*`),
	regexp.MustCompile(`.*per hour for doing work online work.*`),
	regexp.MustCompile(`.*earned \$.* in my first .* month .*`),
	regexp.MustCompile(`.*Porn1MinHD-LBRY.*`),
	regexp.MustCompile(`.*Do you want to make money on your phone?.*`),
	regexp.MustCompile(`.*sigo a todos los que.*`),
	regexp.MustCompile(`.*Comentá para seguir comentando tu publicación.*`),
	regexp.MustCompile(`.*BRASILemEVID.*`),
	regexp.MustCompile(`.*Sígueme de vuelta.*`),
	regexp.MustCompile(`.*Necessito de seguidores.*`),
	regexp.MustCompile(`.*sigo y me siguen.*`),
	regexp.MustCompile(`.*follow me as I follow you.*`),
	regexp.MustCompile(`.*@PremiumPorn.*`),
	regexp.MustCompile(`.*@EvaElfie.*`),
	regexp.MustCompile(`.*@niggertown.*`),
	regexp.MustCompile(`.*generating extra cash online from home more.*`),
	regexp.MustCompile(`.*[Ww]orks[Ss]ilver.*`),
	regexp.MustCompile(`.*[Ww]ork[Jj]oin.*`),
	regexp.MustCompile(`.*[Jj]ob[Cc]ash.*`),
	regexp.MustCompile(`.*[Jj]ob[Aa]pp.*`),
	regexp.MustCompile(`.*for more info visit any tab this site*`),
	regexp.MustCompile(`.*started earning \$.* hour.* in my free time*`),
	regexp.MustCompile(`.*making over \$.* a month working part time*`),
	regexp.MustCompile(`.*making about \$.*-\$.* per month and you can too*`),
	regexp.MustCompile(`.*Please rate my photos at .*`),
	regexp.MustCompile(`.*visit this website.*http.*`),
	regexp.MustCompile(`.*start earning online like me.*`),
	regexp.MustCompile(`.*on the given website.*http*`),
	regexp.MustCompile(`.*start earning cash from your home*`),
	regexp.MustCompile(`(?s).*earning(?s).*http:(?s).*`),
	regexp.MustCompile(`(?s).*money(?s).*http:(?s).*`),
	regexp.MustCompile(`(?s).*euros(?s).*http:(?s).*`),
	regexp.MustCompile(`(?s).*job(?s).*http:(?s).*`),
	regexp.MustCompile(`(?s).*income(?s).*http:(?s).*`),
	regexp.MustCompile(`(?s).*cash(?s).*http:(?s).*`),
	regexp.MustCompile(`(?s).*earn(?s).*http:(?s).*`),
	regexp.MustCompile(`(?s).*earning(?s).*http:(?s).*`),
	regexp.MustCompile(`(?s).*work(?s).*http:(?s).*`),
	regexp.MustCompile(`(?s).*payout(?s).*http:(?s).*`),
	regexp.MustCompile(`(?s).*paid(?s).*http:(?s).*`),
}
