package flags

import "regexp"

var flaggedPhrases = []*regexp.Regexp{
	regexp.MustCompile(`(?mi).*per day online work.*`),
	regexp.MustCompile(`(?mi).*follow me back please.*`),
	regexp.MustCompile(`(?mi).*I earns every weeks.*`),
	regexp.MustCompile(`(?mi).*A White House Memoir by John Bolton.*`),
	regexp.MustCompile(`(?mi).*REPOST THIS VIDEO AND I WILL REPOST 2 YOURS.*`),
	regexp.MustCompile(`(?mi).*All i did was simple online work from.*`),
	regexp.MustCompile(`(?mi).*hr provide by Google.*`),
	regexp.MustCompile(`(?mi).*I heard about this job 3 months.*`),
	regexp.MustCompile(`(?mi).*hour for doing online work from home.*`),
	regexp.MustCompile(`(?mi).*adshrink.it.*`),
	regexp.MustCompile(`(?mi).*I get paid over \$.* per hour working from home.*`),
	regexp.MustCompile(`(?mi).*Free Money - After.*`),
	regexp.MustCompile(`(?mi).*Real online home based job.*`),
	regexp.MustCompile(`(?mi).*I getting Paid upto \$.* this week.*`),
	regexp.MustCompile(`(?mi).*Get your financial freedom out of the hands.*`),
	regexp.MustCompile(`(?mi).*simple online job from home.*`),
	regexp.MustCompile(`(?mi).*She has been fired for .* months but last month.*`),
	regexp.MustCompile(`(?mi).*She has been laid off for .* months but last.*`),
	regexp.MustCompile(`(?mi).*makes \$.*hour.* on the computer.*`),
	regexp.MustCompile(`(?mi).*makes \$.*hour.* on the laptop.*`),
	regexp.MustCompile(`(?mi).*makes \$.*hour.* on the internet.*`),
	regexp.MustCompile(`(?mi).*peau de mouton qui habille et camoufle un loup.*`),
	regexp.MustCompile(`(?mis).*\$.*-\$.* per month on the web.*`),
	regexp.MustCompile(`(?mi).*Help the channel and join you these awesome pages to obtain free crypto coins.*`),
	regexp.MustCompile(`(?mi).*https://lbry.tv/\$./invite/@NiQo:5.*`),
	regexp.MustCompile(`(?mi).*PART TIME ONLINE JOBS.*`),
	regexp.MustCompile(`(?mi).*per hour for doing work online work.*`),
	regexp.MustCompile(`(?mis).*earned \$.* in my first .* month .*`),
	regexp.MustCompile(`(?mi).*Porn1MinHD-LBRY.*`),
	regexp.MustCompile(`(?mi).*Do you want to make money on your phone?.*`),
	regexp.MustCompile(`(?mi).*sigo a todos los que.*`),
	regexp.MustCompile(`(?mi).*Comentá para seguir comentando tu publicación.*`),
	regexp.MustCompile(`(?mi).*BRASILemEVID.*`),
	regexp.MustCompile(`(?mi).*Sígueme de vuelta.*`),
	regexp.MustCompile(`(?mi).*Necessito de seguidores.*`),
	regexp.MustCompile(`(?mi).*sigo y me siguen.*`),
	regexp.MustCompile(`(?mi).*follow me as I follow you.*`),
	regexp.MustCompile(`(?mi).*@PremiumPorn.*`),
	regexp.MustCompile(`(?mi).*@EvaElfie.*`),
	regexp.MustCompile(`(?mi).*@niggertown.*`),
	regexp.MustCompile(`(?mi).*generating extra cash online from home more.*`),
	regexp.MustCompile(`(?mi).*workssilver.*`),
	regexp.MustCompile(`(?mi).*workjoin.*`),
	regexp.MustCompile(`(?mi).*jobcash.*`),
	regexp.MustCompile(`(?mi).*jobapp.*`),
	regexp.MustCompile(`(?mi).*for more info visit any tab this site*`),
	regexp.MustCompile(`(?mis).*started earning \$.* hour.* in my free time*`),
	regexp.MustCompile(`(?mis).*making over \$.* a month working part time*`),
	regexp.MustCompile(`(?mis).*making about \$.*-\$.* per month and you can too*`),
	regexp.MustCompile(`(?mi).*Please rate my photos at .*`),
	regexp.MustCompile(`(?mis).*visit this website.*http.*`),
	regexp.MustCompile(`(?mi).*start earning online like me.*`),
	regexp.MustCompile(`(?mis).*on the given website.*http*`),
	regexp.MustCompile(`(?mi).*start earning cash from your home*`),
	regexp.MustCompile(`(?mis).*money.*http:.*`),
	regexp.MustCompile(`(?mis).*euros.*http:.*`),
	regexp.MustCompile(`(?mis).*job.*http:.*`),
	regexp.MustCompile(`(?mis).*income.*http:.*`),
	regexp.MustCompile(`(?mis).*cash.*http:.*`),
	regexp.MustCompile(`(?mis).*work.*http:.*`),
	regexp.MustCompile(`(?mis).*payout.*http:.*`),
	regexp.MustCompile(`(?mis).*paid.*http:.*`),
	regexp.MustCompile(`(?mi).*I recommend him to anyone with; Herpes Virus.*`),
}
