# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST https://comments.lbry.com/api
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "comment.List",
  "params": {
    "claim_id": "5bd299a92e7b31865d2bb3e2313402edaca41a94",
    "page_size": 200
  }
}



###
