# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:5921/api
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "id": null,
  "method": "abandon",
  "params": {
    "claim_id": "6d266af6c25c80fa2ac6cc7662921ad2e90a07e8",
    "comment": "This is literally, the most anonymous comment I have EVER seen.",
    "channel_id": "9cb713f01bf247a0e03170b5ed00d5161340c486",
    "channel_name": "@bbbbb",
    "signature": "e8ad5dbc268365e5d16f6a9b5d82323efc550412a7a291aa3e715e31641cc57b18241a132ebed28a848086fca6e200a735281c631c7474b01b4c32851ea3dd57",
    "signing_ts": "1561669614"
  }
}

###
